### ISSUE TITLE
lay-out problems in v 1.6

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc_16#1]
Some parts of the screens disappear due to a design and lay-out problem. This prevents users from opening a certain tab of closing an element. 

For example in the manage part you can drag-and-drop elements to add them to your user interface, search form, display template etc. Then you can change the settings by clicking on the i.  A pop-up appears. You can only close this pop-up by clicking on the i at the bottom of the pop-up screen, but this is hidden below the next field and you can't reach it. 
![capture](https://cloud.githubusercontent.com/assets/3798589/23501601/c6e616e8-ff34-11e6-84cf-d65689abf51d.JPG)

Another problem is that part of the page disappears underneath the log-out banner. This happens in several location such as the quick search result list (screen below), but also in the different tabs on record level, or when opening an interstitial element. 
![capture](https://cloud.githubusercontent.com/assets/3798589/23501532/878f80b0-ff34-11e6-9c64-5451764cdee1.JPG)

It's a general problem happening in 1.4, but also in differnet installations of 1.6 (e.g. ca_cct, ca_alamire, and now the new ca_crkc 1.6). It's best we solve this on 1.6 instead of putting our effort into 1.4.

**Comment by naeemmuhammad** [comment]
Fix: https://github.com/libis/ca_crkc_16/commit/9661f6abab573ea90eb3cccc9069e183dc564b88
