### ISSUE TITLE
blank screen when batch editing relationship fields with "remove all values" and "replace value" 

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc_16#2]
Tested in v1.6.3 (local installation as well as CRKC) and noticed some issues with the batch editing function for relationship fields.
Using “Remove all values” and “Replace value” gives a blank screen and no chances are made. The “Add to each” parameter works fine.
Reported to CollectiveAccess, but they don't have this problem and refer to a possible installation issue.
This must be checked before we go live with CRKC since they use the batch editing function often.

http://clangers.collectiveaccess.org/jira/browse/PROV-2026?filter=-2
"We do not see this problem on our test installations. Try setting display_errors = On and see if there's an error message in your install."

Needs to be fixed when going live with 1.6.3

**Comment by naeemmuhammad** [comment]
Fix: https://github.com/libis/ca_crkc_16/commit/10e86457d035bb6f656457e73814d8626c790de5
Corresponding pull request to collective access: https://github.com/collectiveaccess/providence/pull/290 and
https://github.com/collectiveaccess/providence/commit/769566179b4710ac996b57a5f0d486c34dc09d28
