### ISSUE TITLE
search on gives incorrect / no results

### ISSUE THREAD

**Issue by roxannewyns** [libis/ca_crkc_16#4]
**Quick search and Simple search give 0 results when searching on CRKC.0001 and CRKC.0001* (on ca_collections and ca_objects)**

![image](https://user-images.githubusercontent.com/3798589/27287685-da17092c-5504-11e7-9af1-4a6638152c5d.png)

**When I do an * search, the collection and objects of collection are there**
![image](https://user-images.githubusercontent.com/3798589/27287748-fb3da9e4-5504-11e7-8a51-b7616bf8921d.png)

**Comment by naeemmuhammad** [comment]
Fix: https://github.com/libis/heron_configuratie/commit/4f76a6e441188414e59aca04f6b133993f4bd7ff

Collective Access support team suggests to set' INDEX_AS_IDNO' on for this field (Inventarisnummer) to solve this problem. However, setting this parameter on does not solve the problem for us. 

Above mentioned fix solves this problem, but its implications are not yet known.
